### ISSUE TITLE
Overlay is not cleaned up

### ISSUE THREAD

**Issue by appinteractive** [marcelogil/el_tooltip#24]
I did struggle a bit with an issue, where the screen got blocked over time and I couldn't tap on the content in the middle of the screen. After some investigation I found out, that El_Tooltip did not clean up the content inside the Overlay region after being disposed, resulting in tappable but invisible text nodes flying around the app after navigation.

<img width="488" alt="grafik" src="https://github.com/marcelogil/el_tooltip/assets/432828/a8632054-c89a-4ae6-aa31-af178650c072">

I did fix the issue in my Pull-Request #23 for #18.

For testing this fix together with the other fix, use following package config in the pubspec.yaml.

```yaml
el_tooltip:
    git:
      url: https://github.com/appinteractive/el_tooltip
      ref: 62fdea1437e923e0561a4dd7c4e6e73aabeddfdb
```
